mars:
  worker_number: 8

  prometheus:
    http_server_port: 11900
    http_server_ip: 0.0.0.0
    path: /usr/local/webserver/rig-agent-go/rig-agent.sock
    health_enable: true
    health_way: http
    health_path: /health

  xxjob:

  apollo:

  atel:

  eureka: