mars:
  worker_number: 4
  pid_file: /data/www-data/yaml.pid
  #mars的核心功能健康检查
  core:
    env: ENV_NAME
    name: APP_NAME
    http:
      http_port: 11900
      http_ip: 0.0.0.0
      http_timeout: 5
    #健康监测
    health:
      - app: ugcaudit-async-svc
        health_way: pid_file
        health_path: /data/www-data/ugcaudit-async-svc.pid
        http_path: /health/ugcaudit-async-svc
        health_enable: true
      - app: ugcaudit-nweb-api
        health_way: http
        health_port: 10000
        health_ip: 0.0.0.0
        health_path: /health
        http_path: /health/ugcaudit-nweb-api
        health_enable: true
    #普罗米修斯数据监测
    Prometheus:
      http_server_port: 11900
      http_server_ip: 0.0.0.0
      path: /usr/local/webserver/rig-agent-go/rig-agent.sock
      health_path: /health
      metrics_path: /metrics


  extension:


