mars:
  worker_number: 1
  pid_file: /data/www-data/yaml.pid
  #mars的核心功能健康检查
  core:
    env: ENV_NAME
    name: APP_NAME
    http:
      http_port: 11900
      http_ip: 0.0.0.0
      http_timeout: 5
    #健康监测
    health:
      - app: ugcaudit-async-svc
        health_way: pid_file
        health_path: /data/www-data/ugcaudit-async-svc.pid
        http_path: /health/ugcaudit-async-svc
        health_enable: true
      - app: ugcaudit-nweb-api
        health_way: http
        health_port: 80
        health_ip: 0.0.0.0
        health_path: /rig/health.php
        health_host: 0.0.0.0
        health_timeout: 7000
        http_path: /health/ugcaudit-nweb-api
        health_enable: true
    skywalking:
      grpc: "10.64.57.116:11800"
      enable_reg: true
    #普罗米修斯数据监测
    promethean:
      unix_path: /home/zhanglei/ourc/mars-agent/lib/rig-agent.sock
      unix_client_max_buffer: 65535
      http_path: /metrics


  extension:


