// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: register/InstancePing.proto
#ifndef GRPC_register_2fInstancePing_2eproto__INCLUDED
#define GRPC_register_2fInstancePing_2eproto__INCLUDED

#include "skywalking/register/InstancePing.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class ServiceInstancePing final {
 public:
  static constexpr char const* service_full_name() {
    return "ServiceInstancePing";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::Commands* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>> AsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>>(AsyncdoPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>> PrepareAsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>>(PrepareAsyncdoPingRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Commands>* AsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Commands>* PrepareAsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::Commands* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>> AsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>>(AsyncdoPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>> PrepareAsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>>(PrepareAsyncdoPingRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Commands>* AsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Commands>* PrepareAsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_doPing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_doPing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoPing(::grpc::ServerContext* context, ::ServiceInstancePingPkg* request, ::grpc::ServerAsyncResponseWriter< ::Commands>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_doPing<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_doPing() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ServiceInstancePingPkg, ::Commands>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ServiceInstancePingPkg* request, ::Commands* response) { return this->doPing(context, request, response); }));}
    void SetMessageAllocatorFor_doPing(
        ::grpc::experimental::MessageAllocator< ::ServiceInstancePingPkg, ::Commands>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ServiceInstancePingPkg, ::Commands>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* doPing(
      ::grpc::CallbackServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* doPing(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_doPing<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_doPing<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_doPing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_doPing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_doPing() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->doPing(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* doPing(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* doPing(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_doPing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ServiceInstancePingPkg, ::Commands>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ServiceInstancePingPkg, ::Commands>* streamer) {
                       return this->StreameddoPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status doPing(::grpc::ServerContext* /*context*/, const ::ServiceInstancePingPkg* /*request*/, ::Commands* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreameddoPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ServiceInstancePingPkg,::Commands>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_doPing<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_doPing<Service > StreamedService;
};


#endif  // GRPC_register_2fInstancePing_2eproto__INCLUDED
